### ISSUE TITLE
GUI bug when filtering jobs by analyzers 

### ISSUE THREAD

**Issue by amr-cossi** [TheHive-Project/Cortex#119] opened 2018-08-01 15:55 UTC
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       | 16.04
| Cortex version / git hash   | 2.0.4-1
| Package Type              | Docker
| Browser type & version    | Firefox 61.0.1 (64 bits)

### Problem Description
On the main page /index.html#!/jobs, when trying to filter jobs by Analyzers, only the first 25 analyzers are available with no possibility to show the end of the list

### Steps to Reproduce
1. Add and run more than 25 analyzers
2. Go to /index.html#!/jobs
3. Try to filter jobs by analyzers

### Possible Solutions
Allow the user to search for analyzers in the input field by typing a few letters

**Comment by nadouani** [comment] 2018-08-22 15:28
Hello, this is a duplicate of #116 that has been fixed via 2.1.0

**Closed by nadouani** 2018-08-22 15:28 UTC
Labels: duplicate
