### ISSUE TITLE
cant login to 3.0.0-RC3, strips underscore, changes character case

### ISSUE THREAD

**Issue by github-pba** [TheHive-Project/Cortex#206] opened 2019-07-02 12:26 UTC
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu
| OS version (client)       |  Win7
| Cortex version / git hash   | 3.0.0-RC3
| Package Type              |  DEB
| Browser type & version    | IE, Crome 73

### Problem Description
After updating from Cortex 2.x to 3.0.0-RC3, I can no longer log in, because the login screen strips an underscore character from my user name.

A Cortex installation where all Superadmins have special chars in it's name will be unusable after upgrading.

### Steps to Reproduce
1. open Cortex 3.0.0-RC3 login screen
1. enter any username having an underscore (some_user)
1. enter any password
1. open and enable network tracing
1. hit the Sign In button

You will recognize the frontend calls /api/login with the login parameters, but it has mangled the user name and removed the underscore BEFORE sending it to the backend. As a result, the login fails.

![Lost Underscore](https://user-images.githubusercontent.com/50981940/60510963-1a02cd80-9cd1-11e9-81b6-69fef4726748.png)

Capital letters in the user name are converted to lowercase, and many other characters (like äöüß) get converted to spaces, too.

Random&User_Name$with§chars  -> random user name with chars
Günther Müller -> gunter muller

**Comment by nadouani** [comment] 2019-07-02 14:36
This is a duplicate of #199 which is already solved

**Closed by nadouani** 2019-07-02 14:36 UTC
Labels: duplicate
